# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 EPAM Systems
"""
Custom Script builder module
"""


import yaml
import argparse
import base64
import os
import shlex
import subprocess
import sys
import tempfile
from typing import List
from moulin.yaml_wrapper import YamlValue
from moulin.yaml_helpers import YAMLProcessingError
from moulin.utils import construct_dep_cmd
from moulin import ninja_syntax


def get_builder(conf: YamlValue, name: str, build_dir: str, src_stamps: List[str],
                generator: ninja_syntax.Writer):
    """
    Return configured CustomScriptBuilder class
    """
    return CustomScriptBuilder(conf, name, build_dir, src_stamps, generator)


def gen_build_rules(generator: ninja_syntax.Writer):
    """
    Generate custom_script build rules for ninja
    """
    cmd = " && ".join([
        "cd $build_dir",
        "( [ -d $work_dir ] || mkdir $work_dir )",
        "echo '# Code generated by moulin. All manual changes will be lost' > $config_file",
        "echo $b64config | base64 -d - >> $config_file",
    ])
    generator.rule("cs_update_conf",
                   command=cmd,
                   description="Updating config")
    generator.newline()

    cmd = " && ".join([
        "pushd $build_dir > /dev/null",
        "$script $args $config_file",
        "popd > /dev/null",
        construct_dep_cmd(),
    ])
    generator.rule("cs_build",
                   command=f'bash -c "{cmd}"',
                   description="Running custom script",
                   pool="console",
                   restat=True)
    generator.newline()

    prog = os.path.basename(sys.argv[0])
    cmd = " && ".join([
        "pushd $build_dir > /dev/null",
        f"{prog} --utility-builders-custom_script --run-inline-script "
        "--config-file $config_file",
        "popd > /dev/null",
        construct_dep_cmd(),
    ])
    generator.rule("cs_inline_build",
                   command=f'bash -c "{cmd}"',
                   description="Running inline custom script",
                   pool="console",
                   restat=True)
    generator.newline()


def _get_script_args(conf):
    """Return custom_script args as the shell command line would parse them."""
    args = conf.get("args", "")
    if isinstance(args, list):
        return [str(arg) for arg in args]
    if args:
        return shlex.split(str(args))
    return []


def _run_inline_script(config_file: str) -> int:
    """Materialize and run an inline script described by the generated config."""
    with open(config_file, encoding="utf-8") as stream:
        conf = yaml.safe_load(stream)

    inline_script = conf.get("inline_script")
    if inline_script is None:
        raise Exception(f"Config file '{config_file}' does not contain inline_script")

    work_dir = os.path.dirname(config_file) or "."
    script_file = None
    result = None
    try:
        with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                prefix=".moulin-inline-",
                dir=work_dir,
                delete=False) as stream:
            script_file = stream.name
            stream.write(inline_script)

        os.chmod(script_file, 0o700)
        result = subprocess.run([script_file, *_get_script_args(conf), config_file])
    finally:
        if script_file is not None:
            try:
                os.unlink(script_file)
            except FileNotFoundError:
                pass

    if result is None:
        return 1
    return result.returncode


def handle_utility_call(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--run-inline-script", action="store_true")
    parser.add_argument("--config-file", required=True)
    args = parser.parse_args(argv)

    if args.run_inline_script:
        return_code = _run_inline_script(args.config_file)
        if return_code != 0:
            raise SystemExit(return_code)
        return 0

    raise Exception("Unsupported custom_script utility call")


class CustomScriptBuilder:
    """
    CustomScriptBuilder class generates Ninja rules to archive files
    """

    def __init__(self, conf: YamlValue, name: str, build_dir: str, src_stamps: List[str],
                 generator: ninja_syntax.Writer):
        self.conf = conf
        self.name = name
        self.generator = generator
        self.src_stamps = src_stamps
        self.build_dir = build_dir

    def gen_build(self):
        """Generate ninja rules launch custom script"""
        work_dir = self.conf.get("work_dir", "script_workdir").as_str
        common_variables = {
            "work_dir": work_dir,
            "build_dir": self.build_dir,
            "name": self.name,
        }
        script_node = self.conf.get("script", None)
        inline_script_node = self.conf.get("inline_script", None)
        if script_node and inline_script_node:
            raise YAMLProcessingError("'script' and 'inline_script' are mutually exclusive",
                                      self.conf.mark)
        if not script_node and not inline_script_node:
            raise YAMLProcessingError("Either 'script' or 'inline_script' is required",
                                      self.conf.mark)

        if inline_script_node:
            inline_script_node.as_str
            build_rule = "cs_inline_build"
        else:
            build_rule = "cs_build"
            common_variables["script"] = script_node.as_str

        local_conf_file = os.path.join(work_dir, f"conf-{self.name}.yaml")
        local_conf_target = os.path.join(self.build_dir, local_conf_file)
        serialized_conf = yaml.serialize(self.conf._node)
        conf_bytes = serialized_conf.encode("utf-8")
        b64bytes = base64.b64encode(conf_bytes)
        b64conf = b64bytes.decode("utf-8")
        targets = self.get_targets()
        additional_deps_node = self.conf.get("additional_deps", None)
        deps = list(self.src_stamps)
        if additional_deps_node:
            deps.extend([d.as_str for d in additional_deps_node])
        deps.append(local_conf_target)
        self.generator.build(local_conf_target, "cs_update_conf", variables=dict(
            common_variables,
            b64config=b64conf,
            config_file=local_conf_file))
        self.generator.newline()

        self.generator.build(f"conf-{self.name}", "phony", local_conf_target)
        self.generator.newline()

        args_node = self.conf.get("args", "")
        if args_node.is_list:
            args = " ".join([x.as_str for x in args_node])
        else:
            args = args_node.as_str
        self.generator.build(targets, build_rule, deps, variables=dict(
            common_variables,
            config_file=local_conf_file,
            args=args))
        self.generator.newline()

        return targets

    def get_targets(self):
        "Return list of targets that are generated by this build"
        return [t.as_str for t in self.conf["target_images"]]

    def capture_state(self):
        """
        This method should capture state for reproducible builds.
        Luckily, there is nothing to do, as this builder just arhives
        existing files
        """
