# SPDX-License-Identifier: Apache-2.0
# Copyright 2021 EPAM Systems
"""
Yocto builder module
"""

import os
import shlex
from typing import List, Tuple, cast
from moulin.utils import create_stamp_name, construct_dep_cmd
from moulin import ninja_syntax
from moulin.yaml_wrapper import YamlValue
from moulin.yaml_helpers import YAMLProcessingError
import logging
import sys
import subprocess
import argparse
import re
from pathlib import Path


YOCTO_CORE_LAYERS = ["../poky/meta", "../poky/meta-poky", "../poky/meta-yocto-bsp", "../openembedded-core/meta"]
# Moulin keeps the variable list, but BitBake provides the actual paths. TOPDIR
# is set by BitBake; the other variables are OE-Core/Poky build directories
# normally defined from TOPDIR/TMPDIR in meta/conf/bitbake.conf. BUILDHISTORY_DIR
# is optional and exists only when buildhistory metadata is enabled.
YOCTO_GENERATED_DIR_VARIABLES = [
    "TOPDIR",
    "TMPDIR",
    "DL_DIR",
    "SSTATE_DIR",
    "PERSISTENT_DIR",
    "CACHE",
    "BUILDHISTORY_DIR",
    "DEPLOY_DIR",
    "PKGDATA_DIR",
    "STAMPS_DIR",
]
log = logging.getLogger(__name__)


def get_builder(conf: YamlValue, name: str, build_dir: str, src_stamps: List[str],
                generator: ninja_syntax.Writer):
    """
    Return configured YoctoBuilder class
    """
    return YoctoBuilder(conf, name, build_dir, src_stamps, generator)


def gen_build_rules(generator: ninja_syntax.Writer):
    """
    Generate yocto build rules for ninja
    """
    # Create build dir by calling poky/oe-init-build-env script
    cmd = " && ".join([
        "cd $yocto_dir",
        "source $distro_dir/oe-init-build-env $work_dir",
    ])
    generator.rule("yocto_init_env",
                   command=f'bash -c "{cmd}"',
                   description="Initialize Yocto build environment",
                   restat=True)
    generator.newline()

    # Minimal CLI: program + --utility-builders-yocto + all args.
    prog = os.path.basename(sys.argv[0])

    # Use --utility-builders-yocto to add and remove BitBake layers
    cmd = (
        f"{prog} "
        "--utility-builders-yocto "
        "--yocto-dir $yocto_dir "
        "--distro-dir $distro_dir "
        "--work-dir $work_dir "
        "--layers $layers "
        "--stamp $out"
    )
    generator.rule("yocto_update_layers",
                   command=f'bash -c "{cmd}"',
                   description="Synchronize Yocto layers with a moulin configuration file",
                   pool="console",
                   restat=True)
    generator.newline()

    # Write own configuration to moulin.conf. Include it in local.conf
    cmd = " && ".join([
        "cd $yocto_dir",
        "echo '# Code generated by moulin. All manual changes will be lost' > $work_dir/conf/moulin.conf",
        "for x in $conf; do echo $$x >> $work_dir/conf/moulin.conf; done",
        "sed \"/require moulin\\.conf/d\" -i $work_dir/conf/local.conf",
        "echo 'require moulin.conf' >> $work_dir/conf/local.conf",
        "touch -r $work_dir/conf/bblayers.conf $work_dir/conf/local.conf",
    ])
    generator.rule(
        "yocto_update_conf",
        command=cmd,
        description="Update local.conf",
    )
    generator.newline()

    # Invoke bitbake. This rule uses "console" pool so we can see the bitbake output.
    cmd = " && ".join([
        "pushd $yocto_dir > /dev/null",
        "source $distro_dir/oe-init-build-env $work_dir",
        "bitbake $target",
        "popd > /dev/null",
        construct_dep_cmd(),
    ])
    generator.rule("yocto_build",
                   command=f'bash -c "{cmd}"',
                   description="Yocto Build: $name",
                   pool="console",
                   deps="gcc",
                   depfile=".moulin_$name.d",
                   restat=True)


def _flatten_yocto_conf(conf: YamlValue) -> List[Tuple[str, str]]:
    """
    Flatten conf entries. While using YAML *entries syntax, we will get list of conf
    entries inside of other list. To overcome this, we need to move inner list 'up'
    """

    # Problem is conf entries that it is list itself
    result: List[Tuple[str, str]] = []
    for entry in conf:
        if not entry.is_list:
            raise YAMLProcessingError("Expected array on 'conf' node", entry.mark)
        if entry[0].is_list:
            result.extend([(x[0].as_str, x[1].as_str) for x in entry])
        else:
            result.append((entry[0].as_str, entry[1].as_str))
    return result


def _flatten_layers(layers_node: YamlValue) -> List[str]:
    """
Flattens a YAML structure representing layers into a list of strings.
This function takes a YAML node representing layers and flattens it into a list of strings.
It processes the input YAML structure, extracting individual layer names as strings and adding
them to the resulting list.
Args:
    layers_node (YamlValue): The YAML node, represents a list of layers.
Returns:
    List[str]: A list of strings, each string represents a layer name.
Example:
    If `layers_node` is a YAML list like this:
    -
     - nested_layer1
     - nested_layer2
    - layer3
    - layer4
    The function will return ['nested_layer1', 'nested_layer2', 'layer3', 'layer4']
"""
    result: List[str] = []
    for entry in layers_node:
        if entry.is_list:
            result.extend([(x.as_str) for x in entry])
        else:
            result.append((entry.as_str))
    return result


def _filter_yocto_core_layers(layers: List[str]) -> List[str]:
    """
By default, Poky adds the following layers:

"meta"
"meta-poky"
"meta-yocto-bsp"

Newer version of OpenEmbedded shuffled layers a bit
and now we don't have "poky" dir at all, but we still have

"openembedded-core/meta"

For more details, you can find information about it here:
https://github.com/yoctoproject/poky/blob/807831067405a465886593df4e3057d3846a0001/documentation/
migration-guides/migration-1.3.rst#bblayersconf
and here:
poky/meta-poky/conf/bblayers.conf.sample

This function checks the list of layers in your Yaml configuration. If it finds Poky default layers,
it outputs a corresponding warning to the user. Such layers will be removed from the final list since
Poky adds them by default on its level.

Please, be aware, that the warning in this function will be changed to an exception soon. Please, adapt
your YAML Moulin configuration files.

    Args:
    - _layers (List[str]): A list of layers to filter.

    Returns:
    - List[str]: A filtered list of layers without the ones added by the Poky by default.
"""
    result: List[str] = []
    for layer in layers:
        if layer in YOCTO_CORE_LAYERS:
            log.warning("You explicitly specified the %s layer. This layer is the default layer in Poky."
                        " Please, remove this layer from your YAML configuration.", layer)
        else:
            result.append(layer)
    return result


def _is_same_or_child_path(child_candidate: str, parent_candidate: str) -> bool:
    # realpath is required for product layers reached through symlinks, e.g.
    # yocto/meta-product -> ../../meta-product, so generated build dirs are
    # matched against their physical BitBake paths.
    child_candidate = os.path.realpath(os.path.abspath(os.path.normpath(child_candidate)))
    parent_candidate = os.path.realpath(os.path.abspath(os.path.normpath(parent_candidate)))
    return os.path.commonpath([child_candidate, parent_candidate]) == parent_candidate


def _get_yocto_generated_dirs(yocto_dir: str, distro_dir: str, work_dir: str) -> List[str]:
    env_prefix = _env_prefix(yocto_dir, distro_dir, work_dir, quiet=True)
    paths: List[str] = []
    for variable in YOCTO_GENERATED_DIR_VARIABLES:
        cmd = " && ".join([
            env_prefix,
            f"bitbake-getvar --ignore-undefined --value {shlex.quote(variable)}",
        ])
        try:
            value = _run_bash(cmd, capture=True).stdout.strip()
        except (OSError, subprocess.CalledProcessError) as exc:
            # Keep compatibility with BitBake versions that may miss a variable,
            # but warn because an incomplete list can leave generated files in deps.
            log.warning("Can't query BitBake generated directory variable %s: %s",
                        variable, exc)
            continue
        if os.path.isabs(value):
            # Only absolute paths can be safely compared with os.walk() results.
            paths.append(os.path.realpath(os.path.abspath(os.path.normpath(value))))
    return sorted(set(paths))


def _get_layer_file_list(layer_path: str, generated_dirs: List[str]) -> List[str]:
    """
    Return layer files, excluding BitBake generated directories.

    Args:
        layer_path: Directory to scan for layer dependency files.
        generated_dirs: Absolute generated directory paths reported by BitBake.
            Matching child directories are removed from os.walk() in-place to
            prevent descent into generated trees. The function prunes before
            traversal, so generated trees are not enumerated file by file.

    Returns:
        Files below layer_path, except files located inside generated_dirs.
    """
    deps: List[str] = []
    for dirpath, dirnames, filenames in os.walk(layer_path):
        if ".git" in dirnames:
            dirnames.remove(".git")

        abs_dirpath = os.path.realpath(os.path.abspath(os.path.normpath(dirpath)))
        if any(_is_same_or_child_path(abs_dirpath, generated_dir)
               for generated_dir in generated_dirs):
            # Stop descent if the walk already entered a generated tree.
            dirnames.clear()
            continue

        for generated_dir in generated_dirs:
            if not _is_same_or_child_path(generated_dir, abs_dirpath):
                continue
            # Generated directory is inside the layer directory. Remove its
            # next path segment from dirnames, because top-down os.walk() uses
            # dirnames as the list of child directories it will visit next.
            relative_path = os.path.relpath(generated_dir, abs_dirpath)
            dirname = relative_path.split(os.sep, 1)[0]
            if dirname in dirnames:
                dirnames.remove(dirname)

        deps.extend(os.path.join(dirpath, filename) for filename in filenames)
    return deps


class YoctoBuilder:
    """
    YoctoBuilder class generates Ninja rules for given build configuration
    """
    def __init__(self, conf: YamlValue, name: str, build_dir: str, src_stamps: List[str],
                 generator: ninja_syntax.Writer):
        self.conf = conf
        self.name = name
        self.generator = generator
        self.src_stamps = src_stamps
        # With yocto builder it is possible to have multiple builds with the same set of
        # layers. Thus, we have two variables - build_dir and work_dir
        # - yocto_dir is the upper directory where layers are stored. Basically, we should
        #   have core layers  in our yocto_dir
        # - work_dir is the build directory where we can find conf/local.conf, tmp and other
        #   directories. It is called "build" by default
        self.yocto_dir = build_dir
        self.work_dir: str = conf.get("work_dir", "build").as_str
        self.base_distro: str = conf.get("base_distro", "poky").as_str

    def _get_external_src(self) -> List[Tuple[str, str]]:
        external_src_node = self.conf.get("external_src", None)
        if not external_src_node:
            return []

        ret: List[Tuple[str, str]] = []
        for key, val_node in cast(YamlValue, external_src_node).items():
            if val_node.is_list:
                path = os.path.join(*[x.as_str for x in val_node])
            else:
                path = val_node.as_str
            path = os.path.abspath(path)
            ret.append((f"EXTERNALSRC:pn-{key}", path))

        return ret

    def gen_build(self):
        """Generate ninja rules to build yocto/poky"""
        common_variables = {
            "yocto_dir": self.yocto_dir,
            "work_dir": self.work_dir,
            "distro_dir": self.base_distro,
        }

        # First we need to ensure that "conf" dir exists
        env_target = os.path.join(self.yocto_dir, self.work_dir, "conf", "local.conf")
        all_deps = self.src_stamps.copy()
        additional_deps_node = self.conf.get("additional_deps", None)
        if additional_deps_node:
            all_deps.extend(
                os.path.normpath(
                    os.path.join(self.yocto_dir, d.as_str)
                )
                for d in additional_deps_node.flattened_list()
            )
        self.generator.build(env_target,
                             "yocto_init_env",
                             all_deps,
                             variables=common_variables)

        # Then we need to add layers
        layers_node = self.conf.get("layers", None)
        if layers_node:
            layers_stamp = create_stamp_name(self.yocto_dir, self.work_dir, "yocto", "layers")
            layers = " ".join(
                shlex.quote(layer)
                for layer in _filter_yocto_core_layers(_flatten_layers(layers_node))
            )
            self.generator.build(layers_stamp,
                                 "yocto_update_layers",
                                 env_target,
                                 variables=dict(common_variables, layers=layers))

        # Next - update local.conf
        local_conf_target = os.path.join(self.yocto_dir, self.work_dir, "conf", "moulin.conf")
        local_conf_node = self.conf.get("conf", None)
        if local_conf_node:
            local_conf = _flatten_yocto_conf(local_conf_node)
        else:
            local_conf = []

        # Handle external sources (like build artifacts from some other build)
        local_conf.extend(self._get_external_src())

        # '$' is a ninja escape character so we need to quote it
        local_conf_lines = [
            shlex.quote(f'{k.replace("$", "$$")} = "{v.replace("$", "$$")}"') for k, v in local_conf
        ]

        self.generator.build(local_conf_target,
                             "yocto_update_conf",
                             layers_stamp if layers_node else env_target,
                             variables=dict(common_variables, conf=" ".join(local_conf_lines)))
        self.generator.newline()

        self.generator.build(f"conf-{self.name}", "phony", local_conf_target)
        self.generator.newline()

        # Next step - invoke bitbake. At last :)
        targets = self.get_targets()
        self.generator.build(targets,
                             "yocto_build",
                             local_conf_target,
                             variables=dict(common_variables,
                                            target=self.conf["build_target"].as_str,
                                            name=self.name))

        return targets

    def get_extra_dep_file_list(self) -> List[str]:
        "Return files from Moulin-managed Yocto layers."
        if "layers" not in self.conf:
            return []
        layers_node = self.conf["layers"]

        deps: List[str] = []
        layers_base = os.path.join(self.yocto_dir, self.work_dir)
        generated_dirs = _get_yocto_generated_dirs(self.yocto_dir, self.base_distro,
                                                   self.work_dir)
        layers = _filter_yocto_core_layers(_flatten_layers(layers_node))
        for layer in layers:
            layer_path = os.path.normpath(os.path.join(layers_base, layer))
            if not os.path.isdir(layer_path):
                raise YAMLProcessingError(f"Can't find Yocto layer directory '{layer_path}'",
                                          layers_node.mark)
            generated_dirs_inside_layer_dir = [
                generated_dir
                for generated_dir in generated_dirs
                if _is_same_or_child_path(generated_dir, layer_path)
            ]

            # Prune generated dirs per containing layer, so explicit layers under
            # work_dir remain trackable.
            deps.extend(_get_layer_file_list(layer_path, generated_dirs_inside_layer_dir))
        return deps

    def get_targets(self):
        "Return list of targets that are generated by this build"
        return [
            os.path.join(self.yocto_dir, self.work_dir, t.as_str)
            for t in self.conf["target_images"].flattened_list()
        ]

    def capture_state(self):
        """
        Update stored local conf with actual SRCREVs for VCS-based recipes.
        This should ensure that we can reproduce this exact build later
        """


def _env_prefix(yocto_dir: str, distro_dir: str, work_dir: str, quiet: bool = False) -> str:
    """
    Return a shell snippet that cd's into yocto_dir and sources
    oe-init-build-env for work_dir.
    """
    # Captured bitbake-getvar output must contain only the requested value.
    stdout_redirect = " >/dev/null" if quiet else ""
    return " && ".join([
        f"cd {shlex.quote(yocto_dir)}",
        f". {shlex.quote(distro_dir)}/oe-init-build-env {shlex.quote(work_dir)}{stdout_redirect}",
    ])


def _run_bash(cmd: str, *, capture=False) -> subprocess.CompletedProcess:
    """Run a bash -lc command."""
    try:
        return subprocess.run(
            ["bash", "-lc", cmd],
            check=True,
            capture_output=capture,
            text=capture,
        )
    except subprocess.CalledProcessError as exc:
        if capture:
            if exc.stdout:
                print(exc.stdout, end="", file=sys.stdout)
            if exc.stderr:
                print(exc.stderr, end="", file=sys.stderr)
        raise


def relative_paths_to_absolute(base: Path, rels: List[str]) -> List[str]:
    return [str((base / rel).resolve(strict=False)) for rel in rels]


def _read_managed_layers(stamp: str) -> List[str]:
    path = Path(stamp)
    if not path.exists():
        return []
    return [
        line.strip()
        for line in path.read_text().splitlines()
        if line.strip()
    ]


def _write_managed_layers(stamp: str, layers: List[str]) -> None:
    Path(stamp).write_text("\n".join(layers) + "\n")


def _parse_layers_output(output: str) -> List[str]:
    """
    Parse the output of 'bitbake-layers show-layers' and return
    canonical absolute layer paths.

    Example command output:

        layer                 path                             priority
        ==============================================================
        meta                  /home/.../yocto/poky/meta        5
        meta-poky             /home/.../yocto/poky/meta-poky   5
        meta-yocto-bsp        /home/.../yocto/poky/meta-yocto-bsp  5
        meta-virtualization   /home/.../yocto/meta-virtualization  8
        meta-oe               /home/.../meta-openembedded/meta-oe  5
        ...
    """

    # Extract the 'path' column with regex
    row_re = re.compile(
        r"^[ \t]*#?[ \t]*\S+[ \t]+(?P<path>.+?)[ \t]+(?:\d+)[ \t]*$",
        re.MULTILINE,
    )
    layer_paths = row_re.findall(output)

    # Canonicalize build layer paths
    return [
        str(Path(p).expanduser().resolve(strict=False))
        for p in layer_paths
    ]


def _compute_layer_sync(current_layers: List[str], previous_managed_layers: List[str],
                        yaml_layers: List[str]) -> Tuple[List[str], List[str]]:
    """
    Compute the set of managed layers that should be removed and added
    to synchronize the current build with the YAML specification.
    """
    # Create sets for efficient lookup during synchronization
    current_layer_paths_set = set(current_layers)
    yaml_layers_set = set(yaml_layers)
    previous_managed_layers_set = set(previous_managed_layers)

    # Consider only layers that are managed by Moulin.
    # External layers reported by bitbake-layers are ignored.
    # Preserve the current relative order of managed layers.
    current_managed_layers = [
        p for p in current_layers
        if p in previous_managed_layers_set or p in yaml_layers_set
    ]

    # Remove only layers that Moulin managed before and that disappeared from YAML.
    to_remove = [
        p for p in previous_managed_layers
        if p not in yaml_layers_set and p in current_layer_paths_set
    ]

    # Add YAML layers that are missing from the current build.
    to_add = [
        p for p in yaml_layers
        if p not in current_layer_paths_set
    ]

    # Check whether simple remove + append-add preserves YAML order.
    expected_after_diff = [
        p for p in current_managed_layers
        if p in yaml_layers_set
    ] + to_add

    if expected_after_diff != yaml_layers:
        # Recreate only Moulin-managed layers in the YAML order.
        to_remove = [
            p for p in current_managed_layers
            if p in current_layer_paths_set
        ]
        to_add = yaml_layers

    return to_remove, to_add


def handle_utility_call(argv: List[str]) -> int:
    """
    Synchronize Yocto build layers with the specification from YAML.

    Moulin manages only layers explicitly defined in YAML or previously
    recorded in the stamp/state file. Layers added externally are ignored.

    Workflow:

      1. If the stamp/state file does not exist:
        - Add all specified YAML layers to the build environment.
        - Store the list of managed layers in the stamp/state file.

      2. If the stamp/state file exists:
        - Run 'bitbake-layers show-layers' to read all active layers.
        - Normalize layer paths.
        - Consider only Moulin-managed layers.
        - Remove layers that were previously managed but disappeared from YAML.
        - Add YAML layers missing from the current build.
        - Recreate managed layers if needed to preserve YAML order.
        - Update the stamp/state file.
    """

    # Parse args
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--yocto-dir", required=True)  # path to Yocto root
    parser.add_argument("--distro-dir", default="poky")  # path to distro inside Yocto root
    parser.add_argument("--work-dir", required=True)  # path to build dir
    parser.add_argument("--layers", nargs="+", required=True)  # YAML layers (relative to yocto root)
    parser.add_argument("--stamp", required=True)  # stamp file path
    args = parser.parse_args(argv)

    # Extract args into local variables
    yaml_layers_str = " ".join(
        shlex.quote(layer)
        for layer in args.layers
    )
    yocto_root = args.yocto_dir
    distro_dir = args.distro_dir
    build_dir = args.work_dir
    stamp_out = args.stamp
    stamp_exists = Path(stamp_out).exists()
    env_prefix = _env_prefix(yocto_root, distro_dir, build_dir)

    # Compute absolute build path
    build_dir_path = Path(build_dir)
    build_dir_abs: Path = (
        build_dir_path if build_dir_path.is_absolute()
        else (Path(yocto_root) / build_dir_path)).resolve(strict=False)

    # Get absolute paths for YAML-specified layers
    yaml_layers_abs: List[str] = relative_paths_to_absolute(build_dir_abs, args.layers)

    # CASE 1: No stamp/state file yet -> add YAML layers and record them as managed by Moulin
    if not stamp_exists:
        _run_bash(" && ".join([
            f"{env_prefix}",
            f"bitbake-layers add-layer {yaml_layers_str}",
        ]))
        _write_managed_layers(stamp_out, yaml_layers_abs)
        return 0

    # CASE 2: State file exists -> sync only Moulin-managed layers
    # Run "bitbake-layers show-layers" to list currently active layers
    layers_output = _run_bash(f"{env_prefix} && bitbake-layers show-layers", capture=True).stdout

    current_layers = _parse_layers_output(layers_output)
    previous_managed_layers = _read_managed_layers(stamp_out)

    to_remove_abs, to_add_abs = _compute_layer_sync(
        current_layers,
        previous_managed_layers,
        yaml_layers_abs,
    )

    remove_cmd = (
        "bitbake-layers remove-layer " +
        " ".join(shlex.quote(p) for p in to_remove_abs)
        if to_remove_abs else ""
    )

    add_cmd = (
        "bitbake-layers add-layer " +
        " ".join(shlex.quote(p) for p in to_add_abs)
        if to_add_abs else ""
    )

    cmd_parts = [env_prefix, remove_cmd, add_cmd]
    cmd = " && ".join(part for part in cmd_parts if part)

    _run_bash(cmd)
    _write_managed_layers(stamp_out, yaml_layers_abs)
    return 0
