# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 EPAM Systems
"""
Zephyr build generator
"""

import os.path
import json
import logging
import subprocess
from typing import List, Optional
from moulin.yaml_wrapper import YamlValue
from moulin import ninja_syntax
from moulin.utils import construct_dep_cmd
from moulin import utils
from moulin.yaml_helpers import YAMLProcessingError

log = logging.getLogger(__name__)


def get_builder(conf: YamlValue, name: str, build_dir: str, src_stamps: List[str],
                generator: ninja_syntax.Writer):
    """
    Return configured Zephyr builder
    """
    return ZephyrBuilder(conf, name, build_dir, src_stamps, generator)


def gen_build_rules(generator: ninja_syntax.Writer):
    """
    Generate Zephyr build rules for ninja
    """
    cmd = " && ".join([
        "pushd $build_dir > /dev/null",
        "source zephyr/zephyr-env.sh",
        "$env west build -p auto -b $board -d $work_dir $target $snippets -- $shields $vars",
        "popd > /dev/null",
        construct_dep_cmd(),
    ])
    generator.rule("zephyr_build",
                   command=f'bash -c "{cmd}"',
                   description="Invoke Zephyr build system",
                   pool="console",
                   deps="gcc",
                   depfile=".moulin_$name.d",
                   restat=True)
    generator.newline()


class ZephyrBuilder:
    """
    ZephyrBuilder class generates Ninja rules for Zephyr build configuration
    """
    def __init__(self, conf: YamlValue, name: str, build_dir: str, src_stamps: List[str],
                 generator: ninja_syntax.Writer):
        self.conf = conf
        self.name = name
        self.generator = generator
        self.src_stamps = src_stamps
        self.build_dir = build_dir

    def gen_build(self):
        """Generate Ninja rules to build Zephyr"""

        env_node = self.conf.get("env", None)
        if env_node:
            env_values = [x.as_str for x in env_node]
        else:
            env_values = []
        env = " ".join(env_values)

        env = utils.escape(env)

        shields_node = self.conf.get("shields", None)
        if shields_node:
            shields_vals = [x.as_str for x in shields_node]
            shields = f'-DSHIELD=\\"{" ".join(shields_vals)}\\"'
        else:
            shields = ""

        snippets_node = self.conf.get("snippets", [])
        snippets = " ".join([f"-S {snip.as_str}" for snip in snippets_node])

        if snippets and shields:
            raise YAMLProcessingError("Both shields and snippets are specified, only one of them is allowed",
                                      self.conf["snippets"].mark)

        vars_node = self.conf.get("vars", None)
        if vars_node:
            vars_vals = [ZephyrBuilder.__escape_vars_vals(x.as_str) for x in vars_node]
            vars_value = " ".join([f"-D{var}" for var in vars_vals])
        else:
            vars_value = ""

        variables = {
            "name": self.name,
            "build_dir": self.build_dir,
            "board": self.conf["board"].as_str,
            "target": self.conf["target"].as_str,
            "work_dir": self.conf.get("work_dir", "zephyr/build").as_str,
            "shields": shields,
            "snippets": snippets,
            "vars": vars_value,
            "env": env,
        }
        targets = self.get_targets()
        deps = list(self.src_stamps)

        additional_deps_node = self.conf.get("additional_deps", None)

        if additional_deps_node:
            deps.extend([d.as_str for d in additional_deps_node])

        self.generator.build(targets, "zephyr_build", deps, variables=variables)
        self.generator.newline()

        return targets

    @staticmethod
    def __escape_vars_vals(var: str) -> str:
        """
        Escape the given variable value.

        Parameters:
        - var (str): The variable value to be escaped.

        Returns:
        - str: The escaped variable value.

        If the variable value starts with "CONFIG_", double quotation mark escaping is added,
        following the:
        https://github.com/zephyrproject-rtos/zephyr/pull/49267/commits/d77597783a4c148b70c389c8996112f8b6d1e5ed
        """
        if var.startswith("CONFIG_"):
            vars_vals = utils.escape(utils.escape(var))
        else:
            vars_vals = utils.escape(var)
        return vars_vals

    def get_targets(self):
        "Return list of targets that are generated by this build"
        return [os.path.join(self.build_dir, t.as_str) for t in self.conf["target_images"]]

    def get_build_file_list(self) -> List[str]:
        """Return files observed by Zephyr/CMake build metadata."""
        work_dir = self.conf.get("work_dir", "zephyr/build").as_str
        zephyr_build_dir = os.path.join(self.build_dir, work_dir)
        deps = set()
        # Combine compiler inputs, discovered headers, CMake configure inputs,
        # and the west manifest without assuming where source files live.
        deps.update(self.__get_compile_commands_files(zephyr_build_dir))
        deps.update(self.__get_ninja_deps_files(zephyr_build_dir))
        deps.update(self.__get_ninja_configure_files(zephyr_build_dir))
        deps.update(self.__get_west_manifest_file())
        if not deps:
            log.warning("Zephyr build metadata did not report any build files for component '%s' in %s",
                        self.name, zephyr_build_dir)
        return sorted(deps)

    @staticmethod
    def __normalize_dep_path(path: str, base_dir: str) -> str:
        if not os.path.isabs(path):
            path = os.path.join(base_dir, path)
        path = os.path.normpath(path)
        if os.path.isabs(path):
            path = os.path.relpath(path)
        return path.replace("$", "$$")

    def __get_compile_commands_files(self, zephyr_build_dir: str) -> List[str]:
        compile_commands = os.path.join(zephyr_build_dir, "compile_commands.json")
        if not os.path.isfile(compile_commands):
            return []

        with open(compile_commands, encoding="utf-8") as stream:
            commands = json.load(stream)

        deps = []
        for command in commands:
            filename = command.get("file", "")
            if not filename:
                continue
            base_dir = command.get("directory", zephyr_build_dir)
            dep = self.__normalize_dep_path(filename, base_dir)
            if os.path.isfile(dep):
                deps.append(dep)
        return deps

    def __get_ninja_deps_files(self, zephyr_build_dir: str) -> List[str]:
        if not os.path.isdir(zephyr_build_dir):
            return []

        result = self.__run_command(
            "ninja deps query",
            ["ninja", "-C", zephyr_build_dir, "-t", "deps"])
        if result.returncode != 0:
            self.__raise_subprocess_failure("ninja deps query", result)

        deps = []
        for line in result.stdout.splitlines():
            if not line.startswith("    "):
                continue
            dep = self.__normalize_dep_path(line.strip(), zephyr_build_dir)
            if os.path.isfile(dep):
                deps.append(dep)
        return deps

    def __get_ninja_configure_files(self, zephyr_build_dir: str) -> List[str]:
        build_ninja = os.path.join(zephyr_build_dir, "build.ninja")
        if not os.path.isfile(build_ninja):
            return []

        paths = self.__get_ninja_query_inputs(zephyr_build_dir)

        deps = []
        for path in paths:
            dep = self.__normalize_dep_path(path, zephyr_build_dir)
            if os.path.isfile(dep):
                deps.append(dep)
        return deps

    @staticmethod
    def __get_ninja_query_inputs(zephyr_build_dir: str) -> List[str]:
        result = ZephyrBuilder.__run_command(
            "ninja build.ninja query",
            ["ninja", "-C", zephyr_build_dir, "-t", "query", "build.ninja"])
        if result.returncode != 0:
            ZephyrBuilder.__raise_subprocess_failure("ninja build.ninja query", result)

        paths = []
        reading_inputs = False
        for line in result.stdout.splitlines():
            if line.startswith("  input:"):
                reading_inputs = True
                continue
            if line == "  outputs:":
                break
            if reading_inputs and line.startswith("    "):
                path = line.strip()
                if path.startswith("|| "):
                    path = path[3:]
                elif path.startswith("| "):
                    path = path[2:]
                paths.append(path)
        return paths

    def __get_west_manifest_file(self) -> List[str]:
        result = self.__run_command(
            "west manifest path query",
            ["west", "manifest", "--path"],
            cwd=self.build_dir)
        if result.returncode != 0:
            self.__raise_subprocess_failure("west manifest path query", result)

        manifest = self.__normalize_dep_path(result.stdout.strip(), self.build_dir)
        return [manifest] if os.path.isfile(manifest) else []

    @staticmethod
    def __run_command(action: str,
                      args: List[str],
                      cwd: Optional[str] = None) -> subprocess.CompletedProcess:
        try:
            return subprocess.run(args,
                                  cwd=cwd,
                                  stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE,
                                  text=True)
        except OSError as err:
            if cwd is None:
                raise RuntimeError(f"{action} failed to start: {err}") from err
            else:
                raise RuntimeError(f"{action} failed to start in {cwd}: {err}") from err

    @staticmethod
    def __raise_subprocess_failure(action: str, result: subprocess.CompletedProcess) -> None:
        raise RuntimeError(
            f"{action} failed with exit code {result.returncode}\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}")

    def capture_state(self):
        """
        This method should capture state for reproducible builds.
        """
