# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8 pytest pyaml
        # Needed by pygit package
        sudo apt-get install python3-pygit2
        # Needed by moulin integration tests
        sudo apt-get install ninja-build
        # Install other dependencies from setup.py
        pip3 install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Run all other tests
        flake8 . --count --max-complexity=12 --max-line-length=120 --statistics
    - name: Test with pytest
      run: |
        pytest
